name: CI-CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show files
        run: ls -la

      - name: Build Docker image
        run: docker build -t glowvia-site .

      - name: Test container
        run: docker run --rm glowvia-site echo "Build successful"