name: CI

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: echo "Test OK"

      - name: Build Docker
        run: docker build -t my-site .
        